"""empty message

Revision ID: 1678e209b1f6
Revises: 
Create Date: 2018-12-06 00:39:08.889970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1678e209b1f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('sign_up_timestamp', sa.DateTime(), nullable=True),
    sa.Column('verification_timestamp', sa.DateTime(), nullable=True),
    sa.Column('current_status_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['current_status_id'], ['status_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('user_friends',
    sa.Column('origin_user', sa.Integer(), nullable=True),
    sa.Column('other_user', sa.Integer(), nullable=True),
    sa.Column('friend_status', sa.String(length=10), nullable=True),
    sa.Column('request_sent_timestamp', sa.DateTime(), nullable=True),
    sa.Column('request_response_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['origin_user'], ['user.id'], ),
    sa.ForeignKeyConstraint(['other_user'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_friends')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_table('status_types')
    # ### end Alembic commands ###
