"""empty message

Revision ID: 7576c1385490
Revises: 42e2d8b8bd49
Create Date: 2018-12-12 21:55:51.672807

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7576c1385490'
down_revision = '42e2d8b8bd49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recurrence_pattern', sa.Column('end_timestamp', sa.DateTime(), nullable=True))
    op.add_column('recurrence_pattern', sa.Column('start_timestamp', sa.DateTime(), nullable=True))
    op.drop_column('recurrence_pattern', 'end_time')
    op.drop_column('recurrence_pattern', 'start_time')
    op.drop_column('recurrence_pattern', 'date')
    op.drop_column('user', 'is_verified')
    op.drop_column('user', 'verification_timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('verification_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('recurrence_pattern', sa.Column('date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('recurrence_pattern', sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('recurrence_pattern', sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=True))
    op.drop_column('recurrence_pattern', 'start_timestamp')
    op.drop_column('recurrence_pattern', 'end_timestamp')
    # ### end Alembic commands ###
