"""empty message

Revision ID: 870cc18fa5d2
Revises: e08d03b9855d
Create Date: 2018-12-14 10:25:21.552645

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '870cc18fa5d2'
down_revision = 'e08d03b9855d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recurrence_pattern', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('recurrence_pattern', sa.Column('end_time', sa.Time(), nullable=True))
    op.add_column('recurrence_pattern', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('recurrence_pattern', sa.Column('start_time', sa.Time(), nullable=True))
    op.drop_column('recurrence_pattern', 'end_timestamp')
    op.drop_column('recurrence_pattern', 'start_timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recurrence_pattern', sa.Column('start_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('recurrence_pattern', sa.Column('end_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('recurrence_pattern', 'start_time')
    op.drop_column('recurrence_pattern', 'start_date')
    op.drop_column('recurrence_pattern', 'end_time')
    op.drop_column('recurrence_pattern', 'end_date')
    # ### end Alembic commands ###
