"""empty message

Revision ID: e08d03b9855d
Revises: 7576c1385490
Create Date: 2018-12-13 12:21:39.841397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e08d03b9855d'
down_revision = '7576c1385490'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filter', sa.Column('name', sa.String(length=100), nullable=True))
    op.add_column('note', sa.Column('is_recurring', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'is_recurring')
    op.drop_column('filter', 'name')
    # ### end Alembic commands ###
